version: "3"
services:
  app:
    build:
      context: application/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
