version: '3'
services:

         app:
          build:
            context: .
            dockerfile: ./application/Dockerfile
          container_name: app
          tty: true
          volumes: 
             - ./application/app/:/app
          working_dir: /app
          command: gunicorn --bind=0.0.0.0 -w4 simple:app
          restart: unless-stopped

         nginx:
          image: nginx:alpine
          volumes:
            - ./conf.d/:/etc/nginx/conf.d
          ports:
            - 8080:8080

         db:
          image: postgres
          container_name: database
          environment:
            - POSTGRES_PASSWORD=P@ssw0rd
          tty: true
          volumes:
            - ./db/:/docker-entrypoint-initdb.d/
