version: '3'
services:

         app:
          build:
            context: .
            dockerfile: Dockerfile
          container_name: app
          tty: true
          volumes: 
             - ./app/:/app
          working_dir: /app
          command: gunicorn --bind=0.0.0.0 -w4 simple:app

         nginx:
          image: nginx:alpine
          volumes:
            - ./conf.d/:/etc/nginx/conf.d
          ports:
            - 8080:8080
