name: CI

on:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: wait 10
        run: sleep 5
      - name: That's all folks!
        run: echo "That's all folks!"
