name: CI

on:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: wait 10
        run: sleep 5
      - name: That's all folks!
        run: echo "That's all folks!"
  dependabot-pr:
    runs-on: ubuntu-latest
    needs: test-job
    if: github.actor == 'abystrov'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto merge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependency update"
          MERGE_METHOD: "rebase"
