name: Continuous Deployment (production)

on:
  push:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Get build URL
        run: echo $BUILD
        env:
          BUILD: github.server_url/github.repository/actions/runs/github.run_id
