name: Continuous Deployment (production)

on:
  push:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Get build URL
        run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
