name: Testing

on:
  release:
    types: [released]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Echo tag name
        run: echo  $test
        env:
          test: ${{ github.event.release.tag_name }}
