name: Continuous Deployment (production)

on:
  pull_request:

jobs:
  dependabot-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'abystrov'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto merge
        uses: reitermarkus/automerge@v1
        with:
          required-labels: dependency update
          merge-method: rebase
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: no
